#!/bin/sh

# Save this file as /etc/network/if-up.d/mod-etc-issue and chmod +x

if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

IPADDR1=`ip a s enp0s3 | grep inet | awk '{ print $2 }' | head -1`
IPADDR2=`ip a s enp0s8 | grep inet | awk '{ print $2 }' | head -1`

# First time, back up /etc/issue
if [ ! -f /etc/issue.orig ]
then
  cp /etc/issue /etc/issue.orig
fi

# "Reset" /etc/issue to original state
cp /etc/issue.orig /etc/issue

# Append IP address to /etc/issue
echo "$IPADDR1 $IPADDR2" >> /etc/issue
cat /etc/issue.orig >> /etc/issue
echo "" >> /etc/issue
